spring:
  profiles:
    active:
  datasource:
    url: jdbc:postgresql://${DATABASE_NAME}:5432/newspaper_db
    username: roman
    password: 1234
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        format_sql: true
        show_sql: true
        connection:
          pool_size: 20